server:
  port: 8086

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

eureka:
  client:
    service-url:
      defaultZoneUrl: http://localhost:8761/eureka
